### ISSUE TITLE
Convert to use jupyter_sphinx?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#10]
The recent update to the msprime documentation uses [jupyter-sphinx](https://github.com/jupyter/jupyter-sphinx) to render live code chunks using jupyter. It seems to work pretty well --- see example [here](https://tskit-dev.github.io/msprime-docs/main/ancestry.html#specifying-samples). We use the same framework to build and deploy the docs, which would ultimately live at ``https://tskit.dev/tutorials``.

I propose we repurpose this repo to use jupyter-sphinx, such that we create a single sphinx site in which each tutorial consists of one rst file (much like the msprime docs is split into files). That is, we move away from using notebooks which have proved to be really tedious as a format for defining tutorials.

Advantages:

1. All the tutorials will be built during CI
2. We're using rst (or perhaps even markdown - should be possible) with chunks of jupyter interspersed and so reviewing and updating the tutorial content through git will be *much* simpler. Also we're using the same frameworks as the msprime docs, so everything should be immediately familiar to devs.
3. We can assign tags and labels to the tutorial content so that we link to the tutorial content downstream using intersphinx.

**Comment by agladstein** [comment]
Perfect! sounds like a plan

**Comment by agladstein** [comment]
This will be repo for all tskit-dev tutorials right? (i.e. tskit and msprime)?

**Comment by jeromekelleher** [comment]
I think so, yeah. I just doesn't make sense to split them up, IMO

**Comment by molpopgen** [comment]
This sounds great.  Only caveat is that the forward simulation tutorial took 30 minutes or so to process on my laptop, iirc.  It runs a bunch of replicates to compare to msprime.

**Comment by jeromekelleher** [comment]
Eek, that's a long time. I was hoping to make this something that gets built each time, but maybe that's not so practical.

I guess if we're going to demonstrate real stuff then it's going to take more than a few seconds to run the notebook sections. Which makes the intial plan of building every tutorial every time (e.g., during development) impractical.

I guess we could have a separate sphinx site for each tutorial then? There is a bit of boilerplate involved, but perhaps it's not too bad. That still doesn't allow for a 30 minute run time per tutorial, though.

**Comment by molpopgen** [comment]
I guess we just bin the current tutorial.  The reader will just have to trust that it is correct, or copy/paste the code out and test for themselves.

**Comment by benjeffery** [comment]
Even 10min would prob be manageable. Would it be possible to get it down to that?

**Comment by molpopgen** [comment]
Maybe, but maybe that isn't the point?  The tutorial should show how, but maybe not follow through all the way?  

One thing we could do for this tutorial is to provide code as source files.  The online tutorial could display, import, and run one example.  But anyone could clone and run more for themselves?

**Comment by petrelharp** [comment]
We could wrap expensive calculations in a method that caches the result and recomputes only if the code has changed? (knitr has an option like this for r+markdown) I don't know how to do this in a way that's invisible in the html, though.

**Comment by jeromekelleher** [comment]
I think keeping the tutorials to being runnable in a few seconds (say, 10 max) is a reasonable constraint to work within. Do you really learn more as a reader by looking at big examples than you do from small ones?

Re the caching, we'll sort of get this for free if we keep each tutorial in a separate RST file. On the first build when you start a new tutorial, sphinx will build all the pages. But, each subsequent build will only make the your tutorial, as there won't be any changes to the others.

It's probably good discipline to build all the tutorials each time, as then we'll find out when stuff breaks.

**Comment by agladstein** [comment]
> Do you really learn more as a reader by looking at big examples than you do from small ones?

I think that's a good question... I think both big examples and small ones have their place. It's nice to see how all the concepts come together. 

> build all the tutorials each time

each time what?

I'm a little confused. For the docs, when do the examples run? Is it every time a user loads the page or? If it's not every time a user loads the page, and just say when there is an update to the code base, then it doesn't seem like a big deal to me if it take up to 30 min to run.

Also, in this setup is it just demos or can users actually interact and run the code?

**Comment by molpopgen** [comment]
I agree on keeping them short.  The first ones were longer because it allowed demonstration that they are correct, and not because the examples were especially big.  That is a plus of the notebook format--I run it locally before committing.  But the notebooks have too many other drawbacks.

I think I'll probably split the current tutorial into some number of different ones.  A mix of external and embedded code will facilitate sharing among them as necessary.  But first, I need to remind myself what's in there to begin with, as it has been a while.

**Comment by jeromekelleher** [comment]
> each time what?
> I'm a little confused. For the docs, when do the examples run? Is it every time a user loads the page or? If it's not every time a user loads the page, and just say when there is an update to the code base, then it doesn't seem like a big deal to me if it take up to 30 min to run.

The examples run at build-time. Just like in msprime or tskit when you run "make docs", the same thing will happen. So, if we go with the outline I'm proposing above, every tutorial will be built every time we update the repo AND every time a tutorial writer checks out the repo and starts writing a new tutorial. (But see the point [above](https://github.com/tskit-dev/tutorials/issues/10#issuecomment-721635525) about caching)

> Also, in this setup is it just demos or can users actually interact and run the code?

It's just demos the way it's one at the moment in msprime (see e.g. [here](https://tskit-dev.github.io/msprime-docs/main/ancestry.html#ploidy), but I think you can also make these executable by turning on [thebe lab support](https://jupyter-sphinx.readthedocs.io/en/latest/#thebelab-support). I haven't tried it out, though.

**Comment by agladstein** [comment]
> The examples run at build-time

In that case, it seems like the run time is mostly relevant for developers and not for the end users? Yeah, so caching seems like a good idea so it doesn't take a long time for tutorial writers.

**Comment by jeromekelleher** [comment]
Obsoleted by jupyter-book.
