### ISSUE TITLE
Tutorial: Using tskit from R

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#11]
A very useful tutorial would be to show how R users can access tskit data using reticulate. See 
https://github.com/tskit-dev/tskit/issues/1080#issuecomment-743239493 for more discussion.

Depends on #10, though. (At  the time of writing, the repo isn't set up as the planned jupyter-sphinx site)

**Comment by molpopgen** [comment]
The following is an R Markdown doc that does the trick:

\# tskit2r

\`\`\`{r setup}
library(reticulate)
\`\`\`

\`\`\`{python}
import msprime
import pandas as pd

ts = msprime.simulate(100)

df = pd.DataFrame({"left":ts.tables.edges.left,
                   "right":ts.tables.edges.right,
                   "parent": ts.tables.edges.parent,
                   "child": ts.tables.edges.child})
\`\`\`

\`\`\`{r}
df = py$df
head(df)
\`\`\`

**Comment by molpopgen** [comment]
The output from the above, as PDF:

![tskit2r](https://user-images.githubusercontent.com/6416159/101928222-2bb8f780-3b8a-11eb-8fab-93175d639f74.png)

**Comment by benjeffery** [comment]
I think so, the R tutorial seems complete.
