### ISSUE TITLE
Make the intro page pretty and welcoming

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#113]
We should make https://tskit.dev/tutorials/intro.html welcoming to students and others who have heard about tree sequences and want to learn more. I'm hoping this is where a google for "tskit tutorials” will end up.

At the moment there’s not even a logo on that page. Perhaps a web designer might like to take a look. I could imagine breaking down the list of tutorials into the various “parts” and having a thumbnail picture for each part, with links to the tutorials in that part beside the thumbnail. Or something like that anyway. It's like the contents page of a book, I guess.

**Comment by jeromekelleher** [comment]
We can't do too much here, as it's generated by JupyterBook. I don't want to put in custom HTML here as it'll just break as JupyterBook is updated.

By all means we should make the content accessible and discoverable, though.

**Comment by hyanwong** [comment]
Perhaps the best would be to look through a few other jupyterbooks and see if there are any nice examples. The gallery is at https://executablebooks.org/en/latest/gallery.html and e.g. https://fairplus.github.io/the-fair-cookbook/content/home.html has a rather bespoke jupyter-book styled intro page. https://inria.github.io/scikit-learn-mooc/ is a bit more standardised, but does have a picture and a logo.
