### ISSUE TITLE
Version pinning issue with matplotlib?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#115]
I'm not able to build the tutorials locally, it seems to be failing around some matplotlib trickery:
```
from IPython.display import SVG
import matplotlib_inline
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')
...
----> 8 matplotlib_inline.backend_inline.set_matplotlib_formats('svg')
      9 
     10 data1 = np.genfromtxt("data/storing_everyone.csv", delimiter=",", usecols=np.arange(1,12), names=True)

AttributeError: module 'matplotlib_inline' has no attribute 'backend_inline'
AttributeError: module 'matplotlib_inline' has no attribute 'backend_inline'
```

Is there some minimum version we need of some package for this? Is there much to be gained from forcing the output to be SVG? (We're not storing the images, are we?)

**Comment by benjeffery** [comment]
I've not been able to find a version that gives that error, but I found the oldest that doesn't trigger other issues and pinned in #121

**Comment by KrisJiang1999** [comment]
Sir, I got the same problem like u, have you found some solutions?
