### ISSUE TITLE
Reorganize tutorials?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#131]
I've always felt like the high-level arrangement of tutorials, although logical, is not quite in the right order. In particular, there are a lot of tutorials at the start, like "ARGs & tree sequences", "simplification", "Tskit & R", etc which have specific uses, but aren't as generally useful as e.g. "Analysing tree sequences". Some people might try working though the tutorials in order, and I think we should try (roughly) to account for this.

Additionally the "What is a tree sequence" is less of a tutorial and more of a high-level overview, whereas the "Basics" and "Getting started" tutee belong as a pair. So how about something like this as a top-level organisation:

- ....
  - Welcome!
  - What is a tree sequence?
- INTRODUCTION
  - Tree sequence basics
  - Getting started with tskit
- STATISTICS AND ANALYSIS
  - Analysing tree sequences
  - Analysing trees
  - Counting topologies
- FURTHER TSKIT TUTORIALS (order within these emphasised as less important)
  - Tables and editing (was "data structures")
  - Simplification
  - Visualization
  - Working with Metadata
  - ARGs as tree sequences
- OTHER LANGUAGES (could go at end?)
  - Tskit and R
  - (could include e.g. a C tute here)
- BACKWARD TIME SIMULATIONS
  - Do you really need mutations?
  - Advanced msprime topics
  - Completing forwards simulations
- FORWARD TIME SIMULATIONS
  - Forward simulations
- DEVELOPMENT
  - Development

I'm not particularly wedded to this, but I thin the current arrangement could do with a bit of thought

**Comment by benjeffery** [comment]
Looks better than the current to me! Maybe "Analysis and Statistics" as the emphasis is that way round?

**Comment by jeromekelleher** [comment]
Looks good to me - shall we try it out?

**Comment by hyanwong** [comment]
> Looks better than the current to me! Maybe "Analysis and Statistics" as the emphasis is that way round?

I put statistics first, as there was a worry that statistics wasn't mentioned prominently enough. Easy to change though.

The "Tree sequence basics" consists of "Terminology and Concepts", so I think we should probably call it just that, which frees up some names for reuse, so that the first few tutes could look something like this:

- INTRODUCTION
  - Welcome!
  - What is a tree sequence?
- TREE SEQUENCE BASICS
  - Terminology and concepts
  - Getting started with tskit
- STATISTICS AND ANALYSIS
