### ISSUE TITLE
New example for editing tree sequences

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#133]
The current example we use for editing a tree sequence is to strip singleton sites. However, this is much more easily accomplished now using `ts.delete_sites()`, so it would be good to use a different example instead. Perhaps something common, like adding or editing metadata?

**Comment by benjeffery** [comment]
Any metadata examples are (hopefully) going to be out of date soon as I plan to add some methods to help with modifying metadata, so maybe something else or wait for that?

**Comment by hyanwong** [comment]
We could use the code that removes clonal subtrees in https://github.com/tskit-dev/tskit/discussions/1220#discussioncomment-409469. I think that's quite a useful one. Or @benjeffery's code that spots duplicate sequences (but does that edit the tree sequence to remove them, and if so, which does it remove?)
