### ISSUE TITLE
Update the demography tutorial

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#17]
It would great if we could update @gtsambos's demography tutorial to take advantage of jupyterbook's features, and also to reflect the (slightly different) msprime 1.0 APIs. Here's some of the things we can do:

- [x] Convert the file from rst to Markdown (slightly tedious, but worth it)
- [x] Change the code blocks to code cells which are executed (deleting the tree images no longer needed)
- [x] Change to use 1.0 APIs, mainly replacing PopulationConfiguration with Population and using sim_ancestry rather than simulate.

@gtsambos, would you like to do this yourself or are you happy for others to take it on?

**Comment by agladstein** [comment]
If @gtsambos doesn't pick this up, I can work on this. But, I may be a bit slow.

**Comment by gtsambos** [comment]
Hmm, this would be a good prod for me to actually practice using sim_ancestry etc! I'm happy to do it -- do you need it immediately?

**Comment by jeromekelleher** [comment]
No immediately @gtsambos, but say, by the end of January would be good. That work for you?

**Comment by jeromekelleher** [comment]
Closed in #57
