### ISSUE TITLE
Tutorial: tskit tables API

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#19]
We want a tutorial to show people how to use the tables API to construct tree sequences from scratch and to edit them.

We can probably adapt content from the tskit tutorial (e.g., https://tskit.readthedocs.io/en/latest/tutorial.html#editing-tree-sequences)

**Comment by hyanwong** [comment]
This is done in #75 , but it forms the body of the `data_structures` tutorial. It's possible that we should rename "data_structures" to "tables API" or "tables and editing", or something (see https://github.com/tskit-dev/tutorials/pull/75#issuecomment-864233917)

**Comment by hyanwong** [comment]
This can be closed now. Tidying up and renaming the data_structures tutorial can be discussed in another issue
