### ISSUE TITLE
Sub-audience tutorials

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tutorials#191]
The new website design links out from the "genetics research" page to a specific tutorial for each of Popgen, statgen, phylogen and development. We need to author these tutorials and then instate the links from the website.

**Comment by hyanwong** [comment]
My idea is to split the current "Getting started" tutorial into separate introductions for popgen, statgen, and phylogenetics. Possible outline at https://docs.google.com/document/d/1GI1DsrOGdMKdigzsLiy2enTu7ToFN1v8cJ57btHWExY/edit

**Comment by jeromekelleher** [comment]
At yesterdays meeting we decided that we needed three pages in a new "part" at the bottom of the toc, called "Tskit for ...", which gives a quick overview of how we think tskit is good for this field,  does the required terminology translations, and some provides pointers to other parts of the tutorial. There should be no real heavy content in these sections.

- Population genetics. Very quick overview, maybe some initial text explaining that trees are good for stuff.
- Phylogenetics. Mostly placeholder, maybe some terminology clarifications and some emphasis on handling big trees and built-in recombination.
- Statistical Genetics. Mostly placeholder. Can mentions things like relatedness stats, Li and Stephens for now.

**Comment by hyanwong** [comment]
This issue can now be closed in favour of #240
