### ISSUE TITLE
Update introgression tutorial

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#20]
This was converted from existing notebooks. Need to 

- [ ] Update simulation code to use 1.0 APIs like sim_ancestry and demography object
- [ ] Make sure the notebook output prints results (we have a few prints that don't seem to do anything)
- [x] Get the plots working 
- [x] Get the tree plot working

**Comment by jeromekelleher** [comment]
Looks like the Jupyter output is because of a general problem, should be fixed easily enough.

**Comment by jeromekelleher** [comment]
Looks like it's timing out when we're building - probably need to rethink the content a bit.

**Comment by hyanwong** [comment]
Sim code now updated in #67, so you can tick the first item on the list off. There's now only one print statement, and it does output something, so I reckon this can be closed.
