### ISSUE TITLE
Navbar no longer expands out

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#221]
When you scroll down, the navber on the right (e.g. below) no longer expands out to reflect the section you are viewing

<img width="575" alt="Screenshot 2023-01-20 at 15 44 59" src="https://user-images.githubusercontent.com/4699014/213742274-cac22987-2e84-4828-8c88-068b5f5a084e.png">

**Comment by benjeffery** [comment]
How odd, I see the same here. I note this isn't happening on tskit docs.

**Comment by hyanwong** [comment]
I wonder if this is linked to #222 ? E.g. if there are some bad JS URLs somewhere?

**Comment by benjeffery** [comment]
Could be - I'm taking this as a shove to move the tutorials over to the new frozen dependencies. Too many things changing to just specify the direct deps.

**Comment by benjeffery** [comment]
Fixed by #224

**Comment by benjeffery** [comment]
Works for me - @hyanwong can you confirm?

**Comment by hyanwong** [comment]
Yep, fine now. Thanks @benjeffery
