### ISSUE TITLE
Adapt content from SMBE workshop

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#26]
https://github.com/DRL/SMBE-SGE-2019/tree/master/Session_1

@gtsambos, most of this is yours. How do you feel about adapting it for use here?

**Comment by hyanwong** [comment]
I've had a look though. I think the most useful bits that aren't now covered by existing tuts are in https://github.com/DRL/SMBE-SGE-2019/blob/master/Session_1/3.Processing_simulation_results.ipynb to do with exporting data and statistical analysis. There's a TODO section for exporting data in the `getting_started.md` tute, so this would be good, although it doesn't mention the (undocumented) `write_ms` function which is noted as a TODO in `getting_started.md`. I guess once those sections have been extracted we can close this issue, though?

**Comment by jeromekelleher** [comment]
Sounds good - but I'm not sure about the ``write_ms`` reference though? This is a very niche operation, no need to mention it in these tutorials IMO

**Comment by hyanwong** [comment]
> Sounds good - but I'm not sure about the `write_ms` reference though? This is a very niche operation, no need to mention it in these tutorials IMO

Sure - I mention it because it was mentioned in the stub by whoever set it up. Happy to drop it.

**Comment by jeromekelleher** [comment]
Let's drop it.
