### ISSUE TITLE
Clarify the reusability of the tutorial code

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#270]
I was copying and pasting some of the tutorial code into a new repo, and realised that we should say somewhere the licence that applies to any code examples? My suggestion is that code snippets in the tutorials should be licensed as liberally as possible, and not even require attribution.

**Comment by jeromekelleher** [comment]
I think code snippets like this as implicitly assume to be "do whatever you want", we probably don't need to worry about assigning a formal license.

The overall repo license is CC-BY, so I think it's fine.

**Comment by hyanwong** [comment]
Yeah, I agree about not having a formal licence. We could say in the index page that code snippets in this repo are "do whatever you want"? I just need a phrasing

**Comment by jeromekelleher** [comment]
I think we can just sentence saying "All code in these tutorials is free to use for whatever purpose (CC-BY)" or something.

I think that's the de-facto anyway, I doubt anyone is not using the code because they are worried about copyright infringement.

**Comment by gregorgorjanc** [comment]
Given that there is a LICENCE file in the repo and a code of conduct, I think this issue can be closed.
