### ISSUE TITLE
msprime/demography: Change order of migration subsections

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tutorials#33]
See [this comment](https://github.com/tskit-dev/msprime/pull/986#pullrequestreview-405271532) by @agladstein 
> Main thing is, I'd reorganize migration section so it goes
>  - mass migration
>     - use case for divergence
>     - use case for admixture
>  - migration
>     - without mass migration
>     - with mass migration (talk about potential issue)

I will do this as the pictures accompanying the text also should be changed.

**Comment by jeromekelleher** [comment]
Closing this as it's out of date now.
