### ISSUE TITLE
Tutorial: tskit data structures

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#36]
We want a high-level tutorial explaining the basics about how the tskit data structures work without getting into the weeds of sort orders and so on.

I've started an outline of this.

**Comment by hyanwong** [comment]
I've just started to look at this. We must remember that there is quite a lot of useful introductory material at https://tskit.dev/tskit/docs/stable/data-model.html including some key definitions, discussion of individuals, etc. Before starting on the tutorial material we should probably thrash out (in this issue?) how to divide up the work between that page and the tutorial. E.g. should we say "Read the `data-model` page first?" and simply dive straight into some examples of e.g. editing a table, or should we perhaps steal some of the material on that page for use in the tutorial?

Either way, we need reciprocal links between the tutorial and the `data-models` page

**Comment by benjeffery** [comment]
A UML-like diagram of the entities in the model would be useful to have.

**Comment by hyanwong** [comment]
Should we put the (Editing tree sequences)[https://tskit.dev/tskit/docs/stable/tutorial.html?highlight=editing#editing-tree-sequences] material in here too? If not, where?

**Comment by hyanwong** [comment]
> A UML-like diagram of the entities in the model would be useful to have.

http://modeling-languages.com/uml-tools/#python ? Or would you do it by hand (and if so, how to stop it going out of date?)

Would you be interested in making such a diagram @benjeffery ? I'm not sure I would know how.

**Comment by benjeffery** [comment]
![tskit_data_model](https://user-images.githubusercontent.com/8552/122758907-42ef4500-d291-11eb-93d3-e7f3a6307b15.png)

Just made this - I think I got the associations right!

**Comment by hyanwong** [comment]
Nice. Is there any way to indicate *which* of the fields in one box refer to the ID in another box? And would heads on the arrows help?

**Comment by benjeffery** [comment]
The arrow heads usually imply aggregation or composition, neither of which seemed appropriate (except maybe a population being an aggregation of nodes?)

**Comment by hyanwong** [comment]
Ah OK. Seems like there is a directionality in the dependency, that's all. Not sure how we indicate that.

**Comment by hyanwong** [comment]
@benjeffery: I've just suggested adding this to the "tables & editing" tutorial (https://github.com/tskit-dev/tutorials/pull/135). But I wonder if

1. It would be better to have an SVG version instead
2. The lines could go from the specific listed items, to make it clear where they come from, e.g. (rough mockup of red lines)

![image](https://user-images.githubusercontent.com/4699014/128523916-5a40a15e-2728-4ae4-b221-7c6edb62a4e2.png)

**Comment by benjeffery** [comment]
Here's the SVG. The UML editor I use doesn't support changing the lines to non-standard postions, but you could do it in the SVG I guess?

[tskit.vpd.svg.zip](https://github.com/tskit-dev/tutorials/files/6954068/tskit.vpd.svg.zip)

**Comment by hyanwong** [comment]
Here's a rearranged version - I think the position of the boxes makes a bit more sense too (but I didn't know that the numbers on the lines represented, so have left those out for the moment). The mutation params have been reordered to put the parent as the first param, for viz reasons. I don't know if we are worried about this.

![tskit2 vpd](https://user-images.githubusercontent.com/4699014/129443459-56b83425-539f-4973-845e-46c597ec0daa.png)

[tskit2.vpd.svg.zip](https://github.com/tskit-dev/tutorials/files/6986294/tskit2.vpd.svg.zip)

**Comment by hyanwong** [comment]
And this version has lines that are a bit less wiggly:

![tskit3 vpd](https://user-images.githubusercontent.com/4699014/129443854-ebdf67c5-5af5-4258-8c7c-8adb894f8e07.png)

**Comment by jeromekelleher** [comment]
I like it, looks great.

**Comment by jeromekelleher** [comment]
We could consider leaving Migration and Provenance out of the "core" data model, for clarity? They are pretty peripheral, and I think it's more important that people "get" the core entities and their relationships that for this to be complete.

**Comment by hyanwong** [comment]
> I like it, looks great.

Thanks. I guess I can substitute it in to PR #135 then?

> We could consider leaving Migration and Provenance out of the "core" data model, for clarity? They are pretty peripheral, and I think it's more important that people "get" the core entities and their relationships that for this to be complete.

That's a good point. I think Provenances isn't too distracting, as it's not connected to anything, but Migrations are a little more complex.

It would also be easy to change the shade of the table colours to highlight the important ones:

![tskit3 vpd](https://user-images.githubusercontent.com/4699014/129532288-7dc68e14-069c-4752-bd3d-aa359694d812.png)

**Comment by jeromekelleher** [comment]
I think shading the Migration would end up being more confusing, as this implies it's special in some way (it's not, it's just that we don't use it much). I think either leave it out completely or keep things as they are above. I agree provenance isn't a big deal.

**Comment by hyanwong** [comment]
Yes, ISWYM. Happy to go with either. Here's a reworked one without provenance and migration. I swapped stuff around to put nodes and edges first.

![tskit4 vpd](https://user-images.githubusercontent.com/4699014/129545182-f7017bd3-a659-4a60-a73c-4bcf015a20aa.png)

**Comment by jeromekelleher** [comment]
Looks good to me, content-wise. The alignment and spacing of the boxes makes me twitch a bit, though :smile: 

What do others think of the content, before we go optimising the presentation?

**Comment by hyanwong** [comment]
> Looks good to me, content-wise. The alignment and spacing of the boxes makes me twitch a bit, though 😄

Yeah, should probably make the site and mutation boxes the same width, and probably the edge and node tables too. I think having the (edge+nodes) and (sites+mutations) at different vertical levels is fine though - they belong together as pairs.

**Comment by hyanwong** [comment]
> What do others think of the content, before we go optimising the presentation?

I had 15 mins to kill before our US meeting so - despite the comment above - I had a quick go at a possibly neater layout, if we want to reduce line wiggle even more (which does help to make it cleaner I think):

![tskit5 vpd](https://user-images.githubusercontent.com/4699014/129577342-86b401ba-115e-4711-ac54-947557e02f3e.png)

**Comment by petrelharp** [comment]
This is great. I have no opinion about the layout.

**Comment by hyanwong** [comment]
> This is great. I have no opinion about the layout.

You think it's sensible to omit provenance and migration then @petrelharp ?

**Comment by petrelharp** [comment]
Depends on the audience - if this is for a "high-level tutorial" that doesn't get into the weeds, as at the start of this thread, then yes, I think skipping them is good.

**Comment by hyanwong** [comment]
I've added the diagram to #135
