### ISSUE TITLE
"What is" overview

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#48]
#46 merged a stub for a top-level "what is a tree sequence" tutorial.

We should fill this in with a *very* high-level overview of what a tree sequence is (maximum 5 minute read).

@hyanwong, are you happy to take this up? We can port in the content you've done for the "learn_details.html" on the website, I think.

**Comment by hyanwong** [comment]
I'm doing this at the moment. This is about half of what I have. Do you like this approach, which gives the details of how a tree sequence is implemented before saying why they are relevant, or do you prefer the intro style of the current `learn_details.html` page which tries to explain why it is the correct approach before showing how it's implemented?

> # What is a tree sequence?
> 
> A succinct tree sequence, or tree sequence for short, represents the relationships
> between a set of DNA sequences. Tree sequences can be used to store genetic data
> efficiently, and enable powerful analysis of millions of whole genomes at a time.
> They can be created by simulation or by inferring relationships from genetic variation.
> 
> As the name suggests, a tree sequence can be represented by a set of trees, as in the
> visualisation below. Here we see the relationships between 10 genomes
> ('a' to 'j') along a short section of chromosome, 1000 base pairs long,
> simulated by `msprime`. For the majority of this length, up to position 715,
> the relationships between the genomes are as indicated by the first tree. The second tree
> shows the relationships between position 715 and 932, and the third from position 932
> until the end.
> 
>  <img width="679" alt="Screenshot 2021-02-09 at 13 49 01" src="https://user-images.githubusercontent.com/4699014/107372680-9381b500-6add-11eb-9b97-f6f2570e0cd4.png">
> 
> The trees describe the ancestry, or *genetic genealogy* of the 10 genomes. This
> can be incredibly informative. For instance, the sequence of letters in each genome
> can be described by placing *mutations* on branches of the trees. Here's how
> that might look in this simulated example:
> 
> <img width="690" alt="Screenshot 2021-02-09 at 13 49 39" src="https://user-images.githubusercontent.com/4699014/107372746-aa280c00-6add-11eb-8e83-de3e13a0bf26.png">
>

**Comment by jeromekelleher** [comment]
I like it. It would be good if we could keep the same headings as are currently in there though, as I've put in links to these at the top-level website. (So, I wouldn't move on to mutations quite that quickly)

**Comment by hyanwong** [comment]
I put them early because I suspect that most people will not understand at first how a tree can represent genetic data. And it's users of genetic datasets that we want to hook.

I'll continue as-is and see how it goes. We can muck around with the order later.

**Comment by hyanwong** [comment]
Need to add an x-axis label "Genome position (base pairs)" to at least the first drawn TS, when tskit 0.3.5 is released.

**Comment by hyanwong** [comment]
This can be closed.
