### ISSUE TITLE
Speed up R install

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#60]
Currently the R install requires about 5 minutes. It would be nice if we could speed this up by using r-cran-x packages from Debian rather than compiling them each time. I had a quick go at this, but it didn't work for me.

**Comment by gregorgorjanc** [comment]
Looking at Install R support at https://github.com/tskit-dev/tutorials/runs/2324468713?check_suite_focus=true I see we need 

```
reticulate
IRkernel
```

Which pulls in these dependencies

```
glue
rlang
cli
ellipsis
fansi
lifecycle
utf8
vctrs
htmltools
pillar
base64enc
jsonlite
rappdirs
Rcpp
repr
evaluate
IRdisplay
pbdZMQ
crayon
uuid
digest
```

I don't have access to a Debian system, but this https://cran.r-project.org/bin/linux/debian/ shows that we can search for the packages using

```
apt-cache search "^r-.*" | sort
```

looking at https://packages.debian.org/search?keywords=r-cran&searchon=names&suite=unstable I got these matches:

```
reticulate  r-cran-reticulate
IRkernel r-cran-irkernel
# maybe this will already pull in all dependencies below [so I stopped at fansi, but happy to list them all]!
glue r-cran-glue
rlang r-cran-rlang
cli r-cran-cli
ellipsis r-cran-ellipsis
fansi r-cran-fansi
lifecycle ...
utf8
vctrs
htmltools
pillar
base64enc
jsonlite
rappdirs
Rcpp
repr
evaluate
IRdisplay
pbdZMQ
crayon
uuid
digest
```

**Comment by gregorgorjanc** [comment]
Maybe installing Debian r-cran-reticulate will also sort out #61!

**Comment by jeromekelleher** [comment]
I tried  ``r-cran-reticulate`` but it fell over with unmeetable dependencies. Seemed like the r-cran packages wanted a different version of r that was installed or something. Maybe if just installed  ``r-cran-reticulate`` on it's own that would do it... I'll try that.

**Comment by gregorgorjanc** [comment]
Did it work?

**Comment by jeromekelleher** [comment]
No - something weird is happening and I gave up. Someone who uses R on Linux would need to look at this I think, I just don't know enough background.

**Comment by brieuclehmann** [comment]
I'm also a Mac user but occasionally use R on rescomp - I'll look into this later in the week (bit swamped atm 😬)
