### ISSUE TITLE
Fix reticulate install

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#61]
In the github actions script we're currently doing this:
```   
        sudo apt-get install r-base-dev
        sudo R -e 'install.packages(c("reticulate", "IRkernel"))'
        R -e 'IRkernel::installspec()'
```

It doesn't look like this is working somehow, because IRKernal for some reason is trying to download and install reticulate from conda-forge. My only guess is that it can't find reticulate somehow.

It would be very helpful if someone how uses R could look at this and see if they can figure it out. Build [here](https://github.com/tskit-dev/tutorials/runs/2324085922?check_suite_focus=true)

**Comment by gregorgorjanc** [comment]
@jeromekelleher the build you refer above is fine - no errors reported.

**Comment by jeromekelleher** [comment]
This build [failed](https://github.com/tskit-dev/tutorials/runs/2324468713?check_suite_focus=true)

**Comment by hyanwong** [comment]
Since there's a merged PR called "Install reticulate from Debian. #62" I guess this can be closed?
