### ISSUE TITLE
Introgression tutorial mentions ARGs

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#70]
AT the moment it says ""To illustrate this, we simulate ancestral recombination graphs (ARGs) under a simple toy history of divergence and admixture", but we then don't run a simulation with "record_full_arg", but only with `record_migrations=True` (which I guess gives some ARG-like nodes, but not the recombination nodes).

The word ARG is mentioned a number of other times in the tut too. Should we perhaps replace this with "tree sequence"?

**Comment by jeromekelleher** [comment]
We should probably avoid the term all right, it's used in the vague "realisation of the coalescent with recombination" sense.

**Comment by hyanwong** [comment]
I'm editing that tut for typos at the moment. Shall I just replace it with "tree sequence" where appropriate, assuming that the reader, if they have got this far, knows what a tree sequence is?

**Comment by hyanwong** [comment]
(Or actually, simply the word "ancestry" will do at the start, I think)

**Comment by jeromekelleher** [comment]
SGTM - we don't have to be too precise I think.
