### ISSUE TITLE
Completing forwards simulations has a "IncompletePopulationMetadataWarning"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#76]
<img width="833" alt="Screenshot 2021-06-16 at 22 20 22" src="https://user-images.githubusercontent.com/4699014/122295405-0ddd9e00-cef1-11eb-9696-2f599404a3a1.png">

**Comment by petrelharp** [comment]
This warning will dissappear after https://github.com/MesserLab/SLiM/issues/169 - but in the meantime, we should mention that the warning is harmless at least.
