### ISSUE TITLE
Use https://nbviewer.jupyter.org/?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tutorials#8]
Seems like quite a nice way to render Jupyter notebooks. Maybe we should use this instead of trying to locally render them as HTML?

**Comment by molpopgen** [comment]
I think this makes some sense.  Is there a way to do it "automatically"/integrated with the git repo?

**Comment by jeromekelleher** [comment]
> Is there a way to do it "automatically"/integrated with the git repo?

Dunno, this is the bit question I guess.

**Comment by jeromekelleher** [comment]
Obsoleted by jupyter-book.
