### ISSUE TITLE
Way to mark tutorials as done or partly done or stubs?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tutorials#98]
It would be rather helpful for encouraging completing tutorials if there was some way to mark a tutorial as complete on the sidebar (or perhaps on the Introduction page, which is currently a stub). That would remind us that which ones need attention. I guess there isn't a plugin to do this somehow (not sure how though: ratio of `todo` text boxes to other content?). But for visitors to the site, we should e.g. grey out the stubs at least.

**Comment by benjeffery** [comment]
I don't know of a quick way to do this automatically - not sure it is worth the effort.

**Comment by hyanwong** [comment]
You're probably right. Depends on how long those uncompleted or tutorial stubs exist.

**Comment by hyanwong** [comment]
I've just seen that  we can set the titles e.g in italics in the markdown files, and they will be displayed as such in the TOC:

<img width="569" alt="Screenshot 2021-06-24 at 11 04 49" src="https://user-images.githubusercontent.com/4699014/123244617-02373c00-d4dc-11eb-8972-f5230915f5ff.png">

And in the file:

```
(sec_simplification)=

# _Simplification_
% remove underscores in title when tutorial is complete or near-complete

:::{todo}
Create content. See https://github.com/tskit-dev/tutorials/issues/52
:::
```

I think this is worth doing, so that on the landing page we can say that tutorials in italics are not yet ready for use. And it would help us see what needs doing at-a-glance. I'll make a PR.

**Comment by jeromekelleher** [comment]
Sure, seems reasonable. We could be even more obvious and make the title "Simplification (WIP)"
